#!/usr/bin/python

'''
Given a file with 1 float per line prints:
mean median stdev min max 25_percentile 75_percentile
'''

import numpy as np
import sys


def get_floats(input_path):
    floats = []
    with open(input_path) as ip:
        floats = map(float, [x for x in ip if len(x) > 0])
    return floats


if len(sys.argv) != 2:
    print 'Expected: stats <input file>'
else:
    input_path = sys.argv[1]
    floats = get_floats(input_path)
    print "mean %f" % np.mean(floats)
    print "median %f" % np.median(floats)
    print "std %f" % np.std(floats)
    print "min %f" % np.min(floats)
    print "max %f" % np.max(floats)
    print "25th percentile %f" % np.percentile(floats, 25)
    print "75th percentile %f" % np.percentile(floats, 75)
